---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pacman 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pacman
subjects:
- kind: ServiceAccount 
  name: pacman
roleRef:
  kind: ClusterRole
  name: pacman 
  apiGroup: rbac.authorization.k8s.io
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pacman
rules:
- apiGroups: [""]
  resources: ["pods","nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-users-secret
type: Opaque 
data:
  database-admin-password: Y2x5ZGU=
  database-name: cGFjbWFu
  database-password: cGlua3k=
  database-user: Ymxpbmt5
  keyfile-value: cjNkaDR0Cg==
